site_name: Papermerge Blog
site_url: https://papermerge.blog

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections

nav:
  - index.md

plugins:
  - blog:
      blog_dir: .
      post_excerpt: optional
  - search
